import { useState } from 'react';
import { generateRoadmap } from '../../services/aiService';
import './Roadmap.css';

import roadmapIcon from '../../assets/roadmap.png';

const LEVELS = ['Beginner', 'Junior', 'Mid-level', 'Senior'];
const TIMELINES = ['1 month', '3 months', '6 months', '12 months'];

const downloadRoadmapPDF = async (roadmap, form) => {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' });

  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const margin = 48;
  const contentW = W - margin * 2;
  let y = 0;

  const COLORS = {
    bg:      [15, 17, 23],
    surface: [24, 28, 39],
    card:    [30, 36, 54],
    accent:  [79, 124, 255],
    green:   [74, 222, 128],
    textPri: [241, 243, 249],
    textMut: [154, 160, 180],
    border:  [40, 46, 62],
    accentBg:[20, 30, 70],
  };

  const fillPage = () => {
    doc.setFillColor(...COLORS.bg);
    doc.rect(0, 0, W, H, 'F');
  };

  const newPage = () => {
    doc.addPage();
    fillPage();
    y = margin;
  };

  const checkSpace = (needed) => {
    if (y + needed > H - margin - 36) newPage();
  };

  const wrapText = (text, maxWidth, fontSize) => {
    doc.setFontSize(fontSize);
    return doc.splitTextToSize(String(text), maxWidth);
  };

  // ── Page 1 background ──
  fillPage();

  // ── Header band ──
  doc.setFillColor(...COLORS.surface);
  doc.roundedRect(margin, 36, contentW, 94, 10, 10, 'F');
  doc.setDrawColor(...COLORS.accent);
  doc.setLineWidth(1.5);
  doc.roundedRect(margin, 36, contentW, 94, 10, 10, 'S');

  // Left accent bar
  doc.setFillColor(...COLORS.accent);
  doc.roundedRect(margin, 36, 5, 94, 3, 3, 'F');

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(...COLORS.textPri);
  const titleLines = wrapText(roadmap.title, contentW - 40, 20);
  titleLines.forEach((line, i) => doc.text(line, margin + 20, 72 + i * 24));

  // Subtitle chips
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.textMut);
  const sub = `${form.role}  ·  ${form.level} → ${form.targetLevel}  ·  ${form.timeline}  ·  ${roadmap.phases.length} phases`;
  doc.text(sub, margin + 20, 104);

  // Date
  doc.setFontSize(8.5);
  doc.text(
    `Generated by Prepify  ·  ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
    margin + 20, 120
  );

  y = 152;

  // ── Phases ──
  roadmap.phases.forEach((phase) => {
    // ── Phase header ──
    checkSpace(52);
    doc.setFillColor(...COLORS.surface);
    doc.setDrawColor(...COLORS.border);
    doc.setLineWidth(1);
    doc.roundedRect(margin, y, contentW, 46, 8, 8, 'FD');

    // Phase pill
    doc.setFillColor(...COLORS.accentBg);
    doc.roundedRect(margin + 14, y + 13, 64, 18, 9, 9, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.accent);
    doc.text(`Phase ${phase.phase}`, margin + 20, y + 25.5);

    // Phase title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12.5);
    doc.setTextColor(...COLORS.textPri);
    doc.text(phase.title, margin + 88, y + 25.5);

    // Duration
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.textMut);
    doc.text(phase.duration, W - margin - 14, y + 25.5, { align: 'right' });

    y += 54;

    // ── Phase body ──
    const colW = contentW / 2 - 14;
    const pad = 16;
    const lineH = 15;
    const labelH = 26;

    // Pre-calculate heights
    const topicBlocks = phase.topics.map(t => wrapText(t, colW - 18, 10));
    const resBlocks   = phase.resources.map(r => wrapText(r, colW - 18, 10));
    const topicH = topicBlocks.reduce((a, b) => a + b.length * lineH + 3, 0);
    const resH   = resBlocks.reduce((a, b) => a + b.length * lineH + 3, 0);
    const bodyH  = pad + labelH + Math.max(topicH, resH) + pad;

    checkSpace(bodyH + 12);

    doc.setFillColor(...COLORS.surface);
    doc.setDrawColor(...COLORS.border);
    doc.setLineWidth(0.75);
    doc.roundedRect(margin, y, contentW, bodyH, 8, 8, 'FD');

    // Divider between columns
    const divX = margin + contentW / 2;
    doc.setDrawColor(...COLORS.border);
    doc.line(divX, y + 10, divX, y + bodyH - 10);

    // ── Topics column ──
    let ty = y + pad;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(...COLORS.textMut);
    doc.text('TOPICS', margin + pad, ty + 10);
    ty += labelH;

    topicBlocks.forEach((lines) => {
      doc.setFillColor(...COLORS.accent);
      doc.circle(margin + pad + 3, ty + 3.5, 2.5, 'F');
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(...COLORS.textPri);
      lines.forEach((line, li) => doc.text(line, margin + pad + 12, ty + li * lineH));
      ty += lines.length * lineH + 3;
    });

    // ── Resources column ──
    const col2X = divX + 14;
    let ry = y + pad;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(...COLORS.textMut);
    doc.text('RESOURCES', col2X, ry + 10);
    ry += labelH;

    resBlocks.forEach((lines) => {
      doc.setFillColor(...COLORS.green);
      doc.circle(col2X + 3, ry + 3.5, 2.5, 'F');
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(...COLORS.textPri);
      lines.forEach((line, li) => doc.text(line, col2X + 12, ry + li * lineH));
      ry += lines.length * lineH + 3;
    });

    y += bodyH + 12;
  });

  // ── Footer on every page ──
  const totalPages = doc.internal.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFillColor(...COLORS.surface);
    doc.rect(0, H - 32, W, 32, 'F');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(...COLORS.textMut);
    doc.text('Generated by Prepify', margin, H - 12);
    doc.text(`Page ${p} of ${totalPages}`, W - margin, H - 12, { align: 'right' });
  }

  const filename = `${roadmap.title.replace(/[^a-z0-9]/gi, '_')}_Roadmap.pdf`;
  doc.save(filename);
};

const PhaseCard = ({ phase }) => {
  const [open, setOpen] = useState(true);

  return (
    <div className={`roadmap-phase-card ${open ? 'phase-open' : ''}`}>
      <button className="phase-toggle" onClick={() => setOpen(!open)}>
        <div className="phase-toggle-left">
          <span className="phase-number">Phase {phase.phase}</span>
          <span className="phase-title-text">{phase.title}</span>
        </div>
        <div className="phase-toggle-right">
          <span className="phase-duration">{phase.duration}</span>
          <span className={`phase-arrow ${open ? 'rotated' : ''}`}>›</span>
        </div>
      </button>

      {open && (
        <div className="phase-body">
          <div className="phase-section">
            <p className="phase-section-label">📚 Topics</p>
            <ul className="phase-list">
              {phase.topics.map((topic, i) => (
                <li key={i}><span className="phase-dot topic-dot" />{topic}</li>
              ))}
            </ul>
          </div>
          <div className="phase-section">
            <p className="phase-section-label">🔗 Resources</p>
            <ul className="phase-list">
              {phase.resources.map((res, i) => (
                <li key={i}><span className="phase-dot resource-dot" />{res}</li>
              ))}
            </ul>
          </div>
        </div>
      )}
    </div>
  );
};

const Roadmap = () => {
  const [form, setForm] = useState({ role: '', level: '', targetLevel: '', timeline: '' });
  const [roadmap, setRoadmap] = useState(null);
  const [loading, setLoading] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const [error, setError] = useState('');

  const handleChange = (e) => {
    setForm(prev => ({ ...prev, [e.target.name]: e.target.value }));
  };

  const handleGenerate = async () => {
    const { role, level, targetLevel, timeline } = form;
    if (!role.trim()) return setError('Please enter a role.');
    if (!level) return setError('Please select your current level.');
    if (!targetLevel) return setError('Please select your target level.');
    if (!timeline) return setError('Please select a timeline.');
    setError('');
    setLoading(true);
    setRoadmap(null);
    try {
      const token = localStorage.getItem('token');
      const res = await generateRoadmap(role, level, targetLevel, timeline, token);
      if (res.success) setRoadmap(res.data);
      else setError(res.message || 'Failed to generate roadmap.');
    } catch (err) {
      setError(err.message || 'Something went wrong.');
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = async () => {
    if (!roadmap) return;
    setDownloading(true);
    try {
      await downloadRoadmapPDF(roadmap, form);
    } catch (err) {
      setError('Failed to generate PDF. Please try again.');
    } finally {
      setDownloading(false);
    }
  };

  const handleReset = () => {
    setRoadmap(null);
    setForm({ role: '', level: '', targetLevel: '', timeline: '' });
    setError('');
  };

  return (
    <div className="roadmap-page">
      <div className="roadmap-header">
        <h1>Roadmap Generator</h1>
        <p>Get a personalized AI-generated learning roadmap to reach your career goal</p>
      </div>

      <div className={`roadmap-form ${roadmap ? 'frozen' : ''}`}>
        <div className="roadmap-form-grid">
          <div className="form-group full-width">
            <label>Role</label>
            <input
              type="text"
              name="role"
              value={form.role}
              onChange={handleChange}
              placeholder="e.g. Frontend Developer, Data Scientist, DevOps..."
              readOnly={!!roadmap}
            />
          </div>

          <div className="form-group">
            <label>Current Level</label>
            <select name="level" value={form.level} onChange={handleChange} disabled={!!roadmap}>
              <option value="">Select level</option>
              {LEVELS.map(l => <option key={l} value={l}>{l}</option>)}
            </select>
          </div>

          <div className="form-group">
            <label>Target Level</label>
            <select name="targetLevel" value={form.targetLevel} onChange={handleChange} disabled={!!roadmap}>
              <option value="">Select target</option>
              {LEVELS.map(l => <option key={l} value={l}>{l}</option>)}
            </select>
          </div>

          <div className="form-group">
            <label>Timeline</label>
            <select name="timeline" value={form.timeline} onChange={handleChange} disabled={!!roadmap}>
              <option value="">Select timeline</option>
              {TIMELINES.map(t => <option key={t} value={t}>{t}</option>)}
            </select>
          </div>
        </div>

        {error && <p className="form-error">{error}</p>}

        <div className="roadmap-action-row">
          {roadmap ? (
            <button className="reset-btn" onClick={handleReset}>Generate New</button>
          ) : (
            <button className="generate-btn" onClick={handleGenerate} disabled={loading}>
              {loading ? <><span className="spinner" /> Generating...</> : 'Generate Roadmap'}
            </button>
          )}
        </div>
      </div>

      {roadmap && (
        <div className="roadmap-result">
          <div className="roadmap-result-header">
            <div className="roadmap-result-meta">
              <img src={roadmapIcon} alt="roadmap" className="icon-roadmap" />
              <div>
                <h2>{roadmap.title}</h2>
                <p className="roadmap-result-sub">
                  {form.level} → {form.targetLevel} · {form.timeline}
                </p>
              </div>
            </div>
            <div className="roadmap-result-actions">
              <span className="roadmap-phase-count">{roadmap.phases.length} Phases</span>
              <button
                className="download-btn"
                onClick={handleDownload}
                disabled={downloading}
                title="Download as PDF"
              >
                {downloading
                  ? <><span className="spinner spinner-dark" /> Exporting...</>
                  : <>↓ Download PDF</>}
              </button>
            </div>
          </div>

          <div className="roadmap-phases">
            {roadmap.phases.map((phase) => (
              <PhaseCard key={phase.phase} phase={phase} />
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default Roadmap;
